---
Metadata:
  AWSToolsMetrics:
    IaC_Generator: "arn:aws:cloudformation:eu-north-1:430241514154:generatedTemplate/d218eaf5-5854-43a8-85a7-8031f2fc75b6"
Resources:
  IAMManagedPolicyPolicyOnlyReadAssume:
    UpdateReplacePolicy: "Retain"
    Type: "AWS::IAM::ManagedPolicy"
    DeletionPolicy: "Retain"
    Properties:
      ManagedPolicyName: "OnlyReadAssume"
      Path: "/"
      Description: ""
      Groups: []
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
        - Resource: "arn:aws:iam::430241514154:role/OnlyReaderRole"
          Action: "sts:AssumeRole"
          Effect: "Allow"
          Sid: "VisualEditor0"
      Roles: []
      Users:
      - "OnlyReader"
  IAMUserOnlyReader:
    UpdateReplacePolicy: "Retain"
    Type: "AWS::IAM::User"
    DeletionPolicy: "Retain"
    Properties:
      Path: "/"
      ManagedPolicyArns:
      - Ref: "IAMManagedPolicyPolicyOnlyReadAssume"
      UserName: "OnlyReader"
      LoginProfile:
        PasswordResetRequired: false
  IAMManagedPolicyPolicyOnlyReader:
    UpdateReplacePolicy: "Retain"
    Type: "AWS::IAM::ManagedPolicy"
    DeletionPolicy: "Retain"
    Properties:
      ManagedPolicyName: "OnlyReader"
      Path: "/"
      Description: ""
      Groups: []
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
        - Resource: "*"
          Action:
          - "ec2:Get*"
          - "ec2:List*"
          - "ec2:Describe*"
          - "sso:Get*"
          - "sso:List*"
          - "sso:Describe*"
          - "iam:Get*"
          - "iam:List*"
          Effect: "Allow"
          Sid: "Statement1"
      Roles:
      - "OnlyReaderRole"
      Users: []
  IAMRoleOnlyReaderRole:
    UpdateReplacePolicy: "Retain"
    Type: "AWS::IAM::Role"
    DeletionPolicy: "Retain"
    Properties:
      Path: "/"
      ManagedPolicyArns:
      - Ref: "IAMManagedPolicyPolicyOnlyReader"
      MaxSessionDuration: 3600
      RoleName: "OnlyReaderRole"
      Description: ""
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
        - Condition: {}
          Action: "sts:AssumeRole"
          Effect: "Allow"
          Principal:
            AWS: "arn:aws:iam::430241514154:root"
